### PR TITLE
feat(search): implement resultType flag

### PR DESCRIPTION
**Pull request by ecxyzzy**
## Description

Add the `resultType` flag that dictates what types of results are returned by the search endpoint. Can be `course` or `instructor`. Behavior is the same as the endpoint currently if not provided.

## How Has This Been Tested?

Tested locally with queries using the new flag.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code involves a change to the database schema.
- [ ] My code requires a change to the documentation.

### CODE REVIEW

**Review by andrew-wang0 — COMMENTED** [review]
Looks good! 👌

There is an oddity though that I didn't catch the first time. The query builder here

```ts
// /apps/api/src/services/search.ts
const toQuery = (query: string) =>
  sql`TO_TSQUERY('english', WEBSEARCH_TO_TSQUERY('english', ${splitAtLastNumber(query)})::TEXT || ':*')`;
```
looks to do some shenanigans to escape stop words, conjunctions, and other symbols

This causes queries such as the following to fail:
`query=i`
`query=or` (maybe beginning a search for organic chem)
`query=the` (maybe beginning a search for theater)

with the following error
```json
{
  "ok": false,
  "message": "syntax error in tsquery: ':*'"
}
```

And queries such as the following do not return any relevant courses:
`query=non-government` (SOC SCI 152A is titled `Non-Government Organization (NGO) Fundamentals`, but the dash symbol `-` negates the word government)

**Comment by ecxyzzy** [comment]
Good catch, thanks! I think this is by design for the `TO_TSQUERY` function, but is definitely not desirable for our uses. Will look into this and put up an additional commit.

**Comment by ecxyzzy** [comment]
Should be fixed now!

For posterity, the `non-government` query was probably exploding because we passed the node into another `TO_TSQUERY` call which expanded it unnecessarily; when I was testing in `psql`, the negation would not happen with `WEBSEARCH_TO_TSQUERY` unless the hyphen begins a lexeme. Escaping the hyphen looks like it helped in this case, and queries containing only stop words will now just return an empty array rather than erroring.

**Review by andrew-wang0 — APPROVED** [review]
Looks Good! :ok_hand:

**Pull request merged**
